name: Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Release plugin
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      # Setup Java 8 with a settings.xml container a server with id github
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Configure Git user
        run: |
          git config user.email "${{github.actor}}@users.noreply.github.com"
          git config user.name "${{github.actor}}"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          mvn -B release:prepare release:perform
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#      - name: Release
#        uses: qcastel/github-actions-maven-release@master
#        with:
#          access-token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
#          version-minor: true
#          git-release-bot-name: "${{github.actor}}"
#          git-release-bot-email: "${{github.actor}}@users.noreply.github.com"
#        env:
#          JAVA_HOME: /usr/lib/jvm/java-1.8-openjdk/
#          GITREPO_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}